# -*- coding: utf-8 -*-
"""wangyicomments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hlpK0H5TZQuPpPsM6o5Yn_R4GJArOTpk
"""

pip install requests

pip install pycrypto

from Crypto.Cipher import AES
from base64 import b64encode
import requests
import json

url = "https://music.163.com/weapi/comment/resource/comments/get?csrf_token="

data = {
    "csrf_token": "",
    "cursor": "-1",
    "offset": "0",
    "orderType": "1",
    "pageNo": "1",
    "pageSize": "20",
    "rid": "R_SO_4_1325711261",
    "threadId": "R_SO_4_1325711261"
}

f = '00e0b509f6259df8642dbc35662901477df22677ec152b5ff68ace615bb7b725152b3ab17a876aea8a5aa76d2e417629ec4ee341f56135fccf695280104e0312ecbda92557c93870114af6c9d05c4f7f0c3685b7a46bee255932575cce10b424d813cfe4875d3e82047b97ddef52741d546b8e289dc6935b3ece0462db0a22b8e7'
g = "0CoJUm6Qyw8W8jud"
e = "010001"
i = "uj2JjSrkMSJfp2dA"

def get_encSecKey():
    return "a5dde72a103d3aab4960494d9015dd6464ef6e0192e1a39031b3a0fc18b798b383d8891c0d4ae88d5995bee52a0dad60bd7b28f9073a03970ae1389f0a3690a5bb724dceb2ce9f59930e28b321e78245ccbe7e11f1949c0178db871d0d459538587e188c20cad6346571a617d4f077c58a7eaee68094dcb011c20da1cbb297d5"

def get_params(data):   # get string
    first = enc_params(data, g)
    second = enc_params(first, i)
    return second   # return params

def to_16(data):
    pad = 16 - len(data) % 16
    data += chr(pad) * pad
    return data

def enc_params(data, key):
    iv = "0102030405060708"
    data = to_16(data)
    aes = AES.new(key=key.encode("utf-8"), mode=AES.MODE_CBC, IV=iv.encode("utf-8"))
    bs = aes.encrypt(data.encode("utf-8"))
    return str(b64encode(bs), "utf-8")   # toString

resp = requests.post(url, data={
    "params": get_params(json.dumps(data)),
    "encSecKey": get_encSecKey()
})

t = resp.json()

print(type(t))

lst = []
k = t["data"]["comments"]
n = 0
for i in k:
   lst.append({"nickname": i["user"]["nickname"], "content": i["content"]})
   n += 1
print(n)
print(lst)

hlst = []
b = t["data"]["hotComments"]
for i in b:
   hlst.append({"nickname": i["user"]["nickname"], "content": i["content"]})
print(hlst)